apiVersion: v1
kind: Service
metadata:
  name: nodeportsvc
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - name: web
    port: 9001
    protocol: TCP
    targetPort: 80
    nodePort: 30081
  - name: multitool
    port: 9002
    targetPort: 8080
    protocol: TCP
    nodePort: 30082
